In [15]:
import os
import numpy as np
import pandas as pd

In [18]:
DATA_DIR = 'data/고소차 Data'
data_files = [os.path.join(DATA_DIR, filename) for filename in os.listdir(DATA_DIR)]

for filename in data_files:
    print(filename)

data/고소차 Data\20191101_20200218 tele_car_req.xlsx
data/고소차 Data\20191101_20200221 고소차정비_테이블.xlsx
data/고소차 Data\20200219_20200318 tele_car_req.xlsx
data/고소차 Data\20200219_20200318 고소차정비_테이블.xlsx
data/고소차 Data\tele_car_get
data/고소차 Data\고소차 신청정보 tele_car_req 20191101-20200220.xlsx
data/고소차 Data\고소차 장비정보.xlsx

In [25]:
list_df = []
list_df.append(pd.read_excel(data_files[0]))
list_df.append(pd.read_excel(data_files[2]))
df = pd.concat(list_df)

In [26]:
df

,eqp_id,req_no,use_date,aply_date,proj_no,blk_no,eqp_spec_code,eqp_req_qty,detl_work_desc,actl_use_emp_no,...,req_st_date,req_st_time,req_fin_date,req_fin_time,arng_cnfm_emp_no,arng_cnfm_emp_name,rgsr_user_id,rgsr_user_name,eqp_kind_code,eqp_kind_desc
0,S-109,20191028023,20191101,99991231,5459,83M,14M,2,발판 설치 및 해체,6323583,...,20191101,800,20191130,1700,400950.0,장정덕,6323582,권수오,S,리프트카
1,S-042,20191018014,20191101,99991231,2483,NaN,14M,4,NaN,296274,...,20191020,800,20191118,1700,417121.0,박삼석,296274,이경환,S,리프트카
2,S-111,20191028022,20191101,99991231,5462,NaN,12M,2,발판 설치 및 해체,6323583,...,20191101,800,20191130,1700,417121.0,박삼석,6323582,권수오,S,리프트카
3,S-099,20191018014,20191101,99991231,2483,NaN,14M,4,NaN,296274,...,20191020,800,20191118,1700,417121.0,박삼석,296274,이경환,S,리프트카
4,S-072,20191029002,20191101,99991231,5455,NaN,12M,4,NaN,273932,...,20191101,800,20191130,1700,403436.0,신현기,273932,도규환,S,리프트카
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12016,N-453,20200306021,20200318,99991231,4324,NaN,38M,12,NaN,429726,...,20200308,800,20200407,1700,417121.0,박삼석,429726,홍순철,N,고소차
12017,N-390,20200221016,20200318,99991231,4320,191,00M,7,NaN,139393,...,20200303,800,20200331,2400,403436.0,신현기,139393,정인열,N,고소차
12018,N-493,20200226014,20200318,99991231,6061,NaN,28M,6,NaN,6428275,...,20200227,800,20200318,1700,400950.0,장정덕,6428275,박종철,N,고소차
12019,N-384,20200226013,20200318,99991231,2481,113,45M,4,NaN,6375241,...,20200303,800,20200331,1700,403436.0,신현기,6374889,강문철,N,고소차
12020,N-266,20200316030,20200318,99991231,6061,10H,38M,5,NaN,6428258,...,20200318,800,20200406,1700,400950.0,장정덕,6427865,박원규,N,고소차

In [27]:
df.to_csv(DATA_DIR + "\고소차 신청 20191101_20200318.csv", header = True, index = True)